In [1]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [ ]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
%time for _ in range(10): my_arr2 = my_arr * 2

In [ ]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

In [ ]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

In [ ]:
data * 10

In [ ]:
data + data


In [ ]:
data.shape

In [ ]:
data.dtype

In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

In [ ]:
arr2.ndim

In [ ]:
arr2.shape

In [ ]:
arr1.dtype

In [ ]:
arr2.dtype

In [ ]:
np.zeros(10)

In [ ]:
np.zeros((3, 6))

In [ ]:
np.empty((2, 3, 2))

In [ ]:
np.arange(15)

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

In [ ]:
arr2.dtype


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

In [ ]:
float_arr = arr.astype(np.float64)
float_arr.dtype

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

In [ ]:
arr.astype(np.int32)

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

In [ ]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

In [ ]:
empty_uint32 = np.empty(8, dtype='int64')
empty_uint32

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
1 / arr

In [ ]:
arr ** 0.5

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

In [ ]:
arr2 > arr

In [ ]:
arr = np.arange(10)
arr

In [ ]:
arr[5]

In [ ]:
arr[5:8]

In [ ]:
arr[5:8] = 12

In [ ]:
arr

In [ ]:
arr_slice = arr[5:8]
arr_slice

In [ ]:
arr_slice[1] = 12345
arr

In [ ]:
arr_slice[:] = 64

In [ ]:
arr

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

In [ ]:
arr2d[0][2]

In [ ]:
arr2d[0, 2]

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

In [ ]:
arr3d[0]


In [ ]:
old_values = arr3d[0].copy()

In [ ]:
arr3d[0] = 42
arr3d

In [ ]:
arr3d[0] = old_values
arr3d

In [ ]:
arr3d[1, 0]

In [ ]:
x = arr3d[1]
x

In [ ]:
x[0]

In [ ]:
arr = np.arange(10)
arr

In [ ]:
arr[1:6]

In [ ]:
arr2d

In [ ]:
arr2d[:2]

In [ ]:
arr2d[:2, 1:]

In [ ]:
arr2d[1, :2]

In [ ]:
arr2d[:2, 2]

In [ ]:
arr2d[:, :1]

In [ ]:
arr2d[:2, 1:] = 0
arr2d

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

In [ ]:
data

In [ ]:
names == 'Bob'

In [ ]:
data[names == 'Bob']

In [ ]:
data[names == 'Bob', 2:]

In [ ]:
data[names == 'Bob', 3]

In [ ]:
names != 'Bob'

In [ ]:
data[~(names == 'Bob')]

In [ ]:
cond = names == 'Bob'
data[~cond]

In [ ]:
mask = (names == 'Bob') | (names == 'Will')
mask

In [ ]:
data[mask]

In [ ]:
data[data < 0] = 0
data

In [ ]:
data[names != 'Joe'] = 7
data

In [ ]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

In [ ]:
arr[[4, 3, 0, 6]]

In [ ]:
arr[[-3, -5, -7]]

In [ ]:
arr = np.arange(32).reshape((8, 4))
arr

In [ ]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [ ]:
arr = np.arange(15).reshape((3, 5))
arr

In [ ]:
arr.T

In [ ]:
arr = np.random.randn(6, 3)
arr

In [ ]:
np.dot(arr.T, arr)

In [ ]:
arr = np.arange(16).reshape((2, 2, 4))


In [ ]:
arr #2a,2b,4

In [ ]:
arr.transpose(2,0,1) #4,2a,2b

In [ ]:
arr #2a,2b,4

In [ ]:
arr.swapaxes(0,1) #2b,2a,4

In [ ]:
arr = np.arange(10)
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
x = np.random.randn(8)
y = np.random.randn(8)
x

In [ ]:
y

In [ ]:
np.maximum(x, y)

In [ ]:
arr = np.random.randn(7) * 5
arr

In [ ]:
remainder, whole_part = np.modf(arr)
remainder

In [ ]:
whole_part

In [ ]:
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.sqrt(arr, arr)

In [ ]:
arr

In [ ]:
np.sqrt(2,arr)

In [ ]:
arr

In [ ]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)
ys

In [ ]:
xs

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
plt.draw()

In [ ]:
plt.close('all')

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [ ]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

In [ ]:
result = np.where(cond, xarr, yarr)
result

In [ ]:
arr = np.random.randn(4, 4)
arr

In [ ]:
arr > 0

In [ ]:
np.where(arr > 0, 2, -2)

In [ ]:
np.where(arr > 0, 2, arr) # set only positive values to 2

In [ ]:
arr = np.random.randn(5, 4)
arr

In [ ]:
arr.mean()

In [ ]:
np.mean(arr)

In [ ]:
arr.sum()

In [ ]:
arr.mean(axis=1)

In [ ]:
arr.mean(axis=0)

In [ ]:
arr.sum(axis=0)

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

In [ ]:
arr.cumsum(axis=0)

In [ ]:
arr.cumsum(axis=1)

In [ ]:
arr.cumprod(axis=1)

In [ ]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

In [ ]:
bools = np.array([False, False, True, False])
bools.any()

In [ ]:
bools.all()

In [ ]:
arr = np.random.randn(6)
arr

In [ ]:
arr.sort()
arr

In [2]:
arr = np.random.randn(5, 3)
arr

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934],
       [ 0.0929,  0.2817,  0.769 ],
       [ 1.2464,  1.0072, -1.2962],
       [ 0.275 ,  0.2289,  1.3529]])

In [ ]:
arr.sort(1)
arr

In [3]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

-1.551714991950571

In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [5]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [6]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [7]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [8]:
arr = np.arange(10)
np.save('some_array', arr)

In [9]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.savez('array_archive.npz', a=arr, b=arr)

In [11]:
arch = np.load('array_archive.npz')

In [12]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [14]:
!rm some_array.npy

In [15]:
!rm array_archive.npz
!rm arrays_compressed.npz